version: '3.5'

services:
  app:
    build:
      context: .docker/php
    environment:
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}?serverVersion=5.7
    volumes:
      - ./app:/var/www/app
    networks:
      - base-symfony-api
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}  
    ports:
      - "4002:3306"
    volumes:
      - .docker/database/dump:/sql
      - .docker/database/data:/var/lib/mysql
    networks:
      - base-symfony-api

  nginx:
    build:
      context: .docker/nginx
    volumes:
      - ./app:/var/www/app:delegated
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/sites:/etc/nginx/sites-available
      - .docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - '8002:80'
    networks:
      - base-symfony-api
    depends_on:
      - app

networks:
  base-symfony-api:
